USE_LD=1
include ../config.mk
NAME=Alsa
CFLAGS += -Wall -Wextra
#LDFLAGS+=-lsporth_dyn
LDFLAGS+=-lasound
CFLAGS += -Wall -Wextra
#LDFLAGS+=/usr/lib/libsporth.a
include ../config_post.mk

#sporth.so: ${OBJ}
#	$(LD) -o $@ $(LDFLAGS) $^
