USE_LD=1 # needed for e.g. sporth static lib
include config.mk
CC=g++
NAME=ProjectM
CFLAGS+=-I.
CFLAGS+=-Iprojectm/src/libprojectM/
LDFLAGS+=-lprojectM -lSDL2
#LDFLAGS+=-lprojectM -lglfw
include ../config_post.mk

