runs:
  using: "composite"
  steps:

  - run: |
      git clone --depth=1 https://github.com/Gwion/Gwion
      cd Gwion
      git submodule init util ast
      for i in $(git submodule | sed -e 's/.* //'); do
        spath=$(git config -f .gitmodules --get submodule.$i.path)
        surl=$(git config -f .gitmodules --get submodule.$i.url)
        git clone --depth 1 $surl $spath
      done
      git submodule update
      make CC=$CC
    shell: bash
