name: MacOs

on:
  push:
    branches: [master]
  pull-request:
     branches: [master]

env:
  CFLAGS: -fsanitize=address -fno-omit-frame-pointer
  LDFLAGS: -fsanitize=address -fno-omit-frame-pointer

jobs:
  build:
    name: MacOs ${{ matrix.cc }} ${{ matrix.double && 'double' || 'float'}}
    runs-on: macos-latest
    env:
      CC: ${{ matrix.cc }}
      USE_DOUBLE: ${{ matrix.double }}
    strategy:
      matrix:
        cc: [gcc, clang]
        double: [0, 1]


    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Gwion
      uses: ./.github/workflows/gwion

    - name: Build Plug
      run: |
        make -C Soundpipe get-soundpipe
        make
      env:
        BASEDIR: ../Gwion
        AUTO_INSTALL_DEPS: 1
