name: Windows

on:
  push:
    branches: [master]
  pull-request:
     branches: [main]

jobs:
  build:
    name: Windows ${{ matrix.double && 'double' || 'float'}}
    runs-on: windows-latest
    env:
      CC: gcc
      USE_DOUBLE: ${{ matrix.double }}
      BUILD_ON_WINDOWS: 1
    strategy:
      matrix:
        double: [0, 1]


    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Gwion
      uses: ./.github/workflows/gwion

    - name: Build Plug
      run: make
      env:
        BASEDIR: ../Gwion
        AUTO_INSTALL_DEPS: 1
